# Excerci 1
Crea un np.array d'una dimensió, que inclogui l'almenys 8 nombres sencers, data type int64. Mostra la dimensió i la forma de la matriu.

In [1]:
import numpy as np

In [2]:
x = np.array([17,9,14,81,29,8,14,23,4,6,1,2011], dtype="int64")

In [3]:
x.dtype

dtype('int64')

# Excerci 2
De la matriu de l'exercici 1, calcula el valor mitjà dels valors introduïts i resta la mitjana resultant de cada un dels valors de la matriu.

In [6]:
np.median(x)

14.0

In [7]:
x - np.median(x)

array([   3.,   -5.,    0.,   67.,   15.,   -6.,    0.,    9.,  -10.,
         -8.,  -13., 1997.])

# Excerci 3
Crea una matriu bidimensional amb una forma de 5 x 5. Extreu el valor màxim de la matriu, i els valors màxims de cadascun dels seus eixos.

In [8]:
y = np.array([[3,8,45,6,3], [8,33,844,7,101]])

print(y)

[[  3   8  45   6   3]
 [  8  33 844   7 101]]


In [9]:
np.max(y)

844

In [10]:
np.min(y)

3

In [11]:
np.max(y, axis=0)

array([  8,  33, 844,   7, 101])

In [12]:
np.max(y, axis=1)

array([ 45, 844])